name: Deploy to GCS

on:
  push:
    branches:
      - main  # or any branch you prefer

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: gcs-project

    - name: Zip code
      run: zip -r release.zip .

    - name: Upload to GCS
      run: gsutil cp release.zip gs://test1-surya-bucket/path/to/release.zip
