name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Upload to GCS
      run: gsutil -m cp src/*.py gs://test1-surya-bucket/
